import { MIN_PASSWORD_LENGTH, SMS_CODE_LENGTH } from './numbers'

export const PleaseConfirmYourPasswordMsg = 'Пароли не совпадают'
export const NeedConfirmField = 'Необходимо заполнить'
export const CodeMustContainCaetrainLength = `Код должен содержать ${SMS_CODE_LENGTH} цифр`
export const PasswordIsTooShortMsg = `Пароль должен содержать не менее ${MIN_PASSWORD_LENGTH} символов`
export const PleaseInputYourPasswordMsg = 'Пожалуйста, введите пароль'
export const PleaseInputYourNameMsg = 'Пожалуйста, введите ваше ФИО'
export const NameInvalidCharMessage = 'Введен недопустимый символ'
export const NameMustContainMsg = 'Необходимо заполнить'
export const NameMustNotStartOrAndMsg = 'ФИО не может начинаться с этого символа'
export const EmailIsNotValidMsg = 'Необходимо ввести валидный Email'
export const WrongPhoneFormatMsg = 'Неверный формат телефона'
export const PleaseReloadPageMsg = 'Произошла ошибка, пожалуйста, обновите страницу'
export const WrongLoginOrPasswordMsg = 'Неверный логин или пароль'
export const UserAlreadyExitsMsg = 'Пользователь уже зарегистрирован'
export const SendNewSmsCodeMsg = 'Вам отправлен новый смс-код'
export const WrongSmsCodeMsg = 'Неверный смс-код'
export const LoadingMsg = 'Загрузка...'
export const SuccessSignInMsg = 'Вы успешно вошли в аккаунт'