import { MIN_PASSWORD_LENGTH, SMS_CODE_LENGTH } from './numbers'

export const PleaseConfirmYourPasswordMsg = 'Пароли не совпадают'
export const NeedConfirmField = 'Необходимо заполнить'
export const CodeMustContainCaetrainLength = `Код должен содержать ${SMS_CODE_LENGTH} цифр`
export const PasswordIsTooShortMsg = `Пароль должен содержать не менее ${MIN_PASSWORD_LENGTH} символов`
export const PleaseInputYourPasswordMsg = 'Пожалуйста, введите пароль'
export const PleaseReloadPageMsg = 'Произошла ошибка, пожалуйста, обновите страницу'
export const WrongLoginOrPasswordMsg = 'Неверный логин или пароль'
export const UserAlreadyExitsMsg = 'Пользователь с таким телефоном уже зарегистрирован'
export const SendNewSmsCodeMsg = 'Вам отправлен новый смс-код'
export const WrongSmsCodeMsg = 'Неверный смс-код'
export const LoadingMsg = 'Загрузка...'
export const SuccessSignInMsg = 'Вы успешно вошли в аккаунт'
export const SuccessResetPasswordMsg = 'Вы успешно сменили пароль'
export const SuccessRegistrationMsg = 'Вы успешно зарегистрировались'
export const PleaseInputYourNameMsg = 'Пожалуйста, введите ваше Ф. И. О.'
export const PersonNameMustContainMsg = 'Введен недопустимый символ'
export const PersonNameMustNotStartOrAndMsg = 'ФИО не может начинаться с этого символа'
export const PleaseInputCircleNameMsg = 'Пожалуйста, введите название кружка'
export const PleaseInputAddressMsg = 'Пожалуйста, введите адрес кружка'
export const PleaseInputRoomMsg = 'Пожалуйста, введите помещение кружка'
export const CharactersTopLimitMsg = (limit: number) => `Не разрешается вводить больше ${limit} символов`
export const CharactersBottomLimitMsg = (limit: number) => `Не разрешается вводить меньше ${limit} символов`
export const EmailIsNotValidMsg = 'Необходимо ввести валидный Email'
export const WrongPhoneFormatMsg = 'Неверный формат телефона'
export const PleaseInputYourEmailMsg = 'Пожалуйста, введите ваш Email'
export const PleaseSelectOneOfOptionsMsg = 'Пожалуйста, выберите один из вариантов'
export const SuccessInviteEmployeeMsg = 'Приглашение отправлено'
export const SuccessCreateCircleMsg = 'Кружок успешно создан'
