export const enum AppRoutes {
    AUTH = 'auth',
    AUTH_SIGN_IN = 'auth_signin',
    AUTH_REGISTER = 'auth_register',
    AUTH_FORGOT = 'auth_forgot',
    CIRCLE_LIST = 'circle',
    CIRCLE_CREATE = 'circle_create',
    EMPLOYEE_LIST = 'employee_list',
    EMPLOYEE_CREATE = 'employee_create',
    MAIN = 'main',
    MOBILE_RECAPTCHA = 'mobile_recaptcha',
    NOT_FOUND = 'not_found',
    QUERY_LIST = 'query_list',
    STUDENT_LIST = 'student_list',
    STUDENT_CREATE = 'student_create',
    USER_LIST = 'user_list',
    USER_EDIT = 'user_edit',
}

export const RoutePath: Record<AppRoutes, string> = {
    [AppRoutes.AUTH]: '/auth',
    [AppRoutes.AUTH_SIGN_IN]: '/auth/signin',
    [AppRoutes.AUTH_REGISTER]: '/auth/register',
    [AppRoutes.AUTH_FORGOT]: '/auth/forgot',
    [AppRoutes.CIRCLE_LIST]: '/circle',
    [AppRoutes.CIRCLE_CREATE]: '/circle/create',
    [AppRoutes.EMPLOYEE_LIST]: '/employee',
    [AppRoutes.EMPLOYEE_CREATE]: '/employee/create',
    [AppRoutes.MAIN]: '/',
    [AppRoutes.MOBILE_RECAPTCHA]: '/mobile-recaptcha',
    [AppRoutes.NOT_FOUND]: '/404',
    [AppRoutes.QUERY_LIST]: '/query',
    [AppRoutes.STUDENT_LIST]: '/student',
    [AppRoutes.STUDENT_CREATE]: '/student/create',
    [AppRoutes.USER_LIST]: '/user',
    [AppRoutes.USER_EDIT]: '/user/edit',
}
